// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOoJrcwfVEoVPwC37_FGcpvSapRdQ_s4c',
    appId: '1:140170049224:android:af16990b1db73b7bf897fd',
    messagingSenderId: '140170049224',
    projectId: 'learnlens-6c98c',
    storageBucket: 'learnlens-6c98c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_jz3XQSEzZYWhwAwmWerQkFbWzt3-AzY',
    appId: '1:140170049224:ios:34447589b8814486f897fd',
    messagingSenderId: '140170049224',
    projectId: 'learnlens-6c98c',
    storageBucket: 'learnlens-6c98c.firebasestorage.app',
    iosBundleId: 'com.example.learnlens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_jz3XQSEzZYWhwAwmWerQkFbWzt3-AzY',
    appId: '1:140170049224:ios:34447589b8814486f897fd',
    messagingSenderId: '140170049224',
    projectId: 'learnlens-6c98c',
    storageBucket: 'learnlens-6c98c.firebasestorage.app',
    iosBundleId: 'com.example.learnlens',
  );
}
